#!/usr/bin/env python3
"""Deterministic tests for the bounded installed hydration acceptance probe."""

from __future__ import annotations

import errno
import importlib.util
from pathlib import Path
import sys
import tempfile
import time
import unittest


REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT = REPO_ROOT / ".scripts/acceptance/run_installed_generated_hydration.py"


def load_probe():
    spec = importlib.util.spec_from_file_location("installed_generated_hydration", SCRIPT)
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


probe = load_probe()


class BoundedReadTests(unittest.TestCase):
    def test_exact_bytes_return_with_digest_and_size(self):
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "Messages.md"
            path.write_bytes(b"exact generated bytes\n")
            result = probe.bounded_read(path, timeout=1)
        self.assertFalse(result.timed_out)
        self.assertIsNone(result.errno)
        self.assertEqual(result.byte_count, 22)
        self.assertIsNotNone(result.digest)

    def test_errno_is_retained(self):
        result = probe.bounded_read(Path("/definitely/missing/generated-doc"), timeout=1)
        self.assertFalse(result.timed_out)
        self.assertEqual(result.errno, errno.ENOENT)
        self.assertEqual(result.byte_count, 0)

    def test_timeout_is_bounded_and_child_is_reaped(self):
        original = probe._read_child

        def blocked(_path, _sender):
            time.sleep(60)

        probe._read_child = blocked
        try:
            started = time.monotonic()
            result = probe.bounded_read(Path("unused"), timeout=0.05)
        finally:
            probe._read_child = original
        self.assertTrue(result.timed_out)
        self.assertLess(time.monotonic() - started, 1)


class EvidenceMathTests(unittest.TestCase):
    def test_percentiles_use_nearest_rank_for_twenty_reads(self):
        values = list(range(1, 21))
        self.assertEqual(probe.percentile(values, 0.95), 19)
        self.assertEqual(probe.percentile(values, 0.99), 20)

    def test_hint_delta_requires_balanced_requested_release(self):
        before = {"requested": 3, "visible": 1, "background": 2, "accepted": 6, "unroutable": 0}
        after = {"requested": 23, "visible": 1, "background": 22, "accepted": 46, "unroutable": 0}
        delta = probe.hint_delta(before, after)
        self.assertEqual(delta["requested"], 20)
        self.assertEqual(delta["background"], 20)
        self.assertEqual(delta["unroutable"], 0)


class CursorTests(unittest.TestCase):
    def test_backward_history_and_forward_live_progress_are_monotonic(self):
        before = {"scope": [500, 900, 0, 1000]}
        after = {"scope": [300, 950, 1, 2000]}
        self.assertTrue(probe.cursors_monotonic(before, after))

    def test_regression_or_disappearance_fails_closed(self):
        baseline = {"scope": [500, 900, 1, 2000]}
        for after in (
            {},
            {"scope": [600, 900, 1, 2000]},
            {"scope": [500, 899, 1, 2000]},
            {"scope": [500, 900, 0, 2000]},
            {"scope": [500, 900, 1, 1999]},
        ):
            self.assertFalse(probe.cursors_monotonic(baseline, after))


if __name__ == "__main__":
    unittest.main()
