[package]
name = "tgfs-ff-lander"
version = "0.1.0"
edition = "2024"
rust-version = "1.91"
publish = false

[workspace]

[dependencies]
ed25519-dalek = "2.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha1 = "0.10"

[lints.rust]
missing_docs = "warn"
unreachable_pub = "warn"

[lints.clippy]
all = { level = "deny", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
print_stdout = "deny"
print_stderr = "deny"
dbg_macro = "deny"
